config/routes.rb
Rails.application.routes.draw do

   root 'jobs#index'

  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

	def index
		@jobs = Job.all

	end

	def new 
		@job = Job.new
	end

	def create
    	Job.create(job_params)
  		redirect_to jobs_path
	end

	def edit
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
 		@job.update_attributes(job_params)
  		redirect_to jobs_path
	end

	def destroy
		@job = Job.find(params[:id])
		@job.destroy
		redirect_to jobs_path
	end

private

	def job_params
  		params.require(:job).permit(:title, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
      <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
      </div>
      <div>
        <%= f.label :description %>
        <%= f.text_area :description, size: '40x1' %>
      </div>
      <div>
        <%= f.submit 'submit'%>
      </div>

<% end %>

app/views/jobs/edit.html.erb
<%= render "form" %>

app/views/jobs/index.html.erb
<header>
  <div class="left-nav">
    <ul>
      <li><%= link_to "Home", jobs_path %></li>
    </ul>
  </div>
  <div class="right-nav">
    <ul>
      <li><%= link_to "Add Discussion", new_job_path %></li>
    </ul>
  </div>
  <div class="clearfix"></div>
</header>	

<h1> Hello,Welcome to my board !!!</h1>
<p> you can give me some discussion~~</p>
<p> -------------------------------------------------------------------------------------------------------------------</p>



<% @jobs.each do |job| %>
  <div>

  <h2><%= job.title%></h2>
  <h5><%= job.description %></h5>

  <p><%= button_to "Edit Posting", edit_job_path(job),:method => "get"%></p>
  <p><%= button_to 'Delete Posting', job, :method => :delete, data: { confirm: 'Delete?' } %></p>
  <p> -------------------------------------------------------------------------------------------------------------------</p>
  </div>
<% end %>

app/views/jobs/new.html.erb
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Board</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>